In [3]:
lists = ['a','b','c']
lists.append('d')
print (lists)
# print (len(lists))
# lists.insert(0,'mm')
# lists.pop()
# print (lists)

['a', 'b', 'c', 'd']


In [6]:
lists = ['a','b','c']
lists.append('d')
# print (lists)
print (len(lists))
# lists.insert(0,'mm')

4


In [10]:
lists = ['a','b','c']
lists.append('d')
# print (lists)
# # print (len(lists))
lists.insert(0,'mm')
# lists.pop()
print (lists)

['mm', 'a', 'b', 'c', 'd']


In [11]:
lists = ['a','b','c']
lists.append('d')
# print (lists)
# # print (len(lists))
lists.insert(0,'mm')
lists.pop()
print (lists)

['mm', 'a', 'b', 'c']


In [12]:
tuples = ('tupleA','tupleB')
print (tuples[0])


tupleA


In [13]:
# -*- coding: utf-8 -*
# 定义一个 dictionary
from typing import Dict

score: Dict[str, int] = {'guanyu':95,'zhangfei':96}
# 添加一个元素
score['zhaoyun'] = 98
print (score)
# 删除一个元素
score.pop('zhangfei')
# 查看 key 是否存在
print ('guanyu' in score)
# 查看一个 key 对应的值
print (score.get('guanyu'))
print (score.get('yase',99))


{'guanyu': 95, 'zhangfei': 96, 'zhaoyun': 98}
True
95
99


In [14]:
s = set(['a', 'b', 'c'])
s.add('d')
s.remove('b')
print (s)
print ('c' in s)

{'c', 'a', 'd'}
True


In [22]:
s = set(['a', 'b', 'c'])
s.add('d')
s.remove('b')
print (s)


{'c', 'a', 'd'}


In [30]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b[1,1]=10
print(a.shape)
print(b.shape)
print(a.dtype)
print(b)

(3,)
(3, 3)
int32
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


In [79]:
import numpy as np
persontype = np.dtype({
    'names':['name', 'age', 'chinese', 'math', 'english'],
    'formats':['S32','i', 'i', 'i', 'f']})
peoples = np.array([("ZhangFei",32,75,100, 90),("GuanYu",24,85,96,88.5),
       ("ZhaoYun",28,85,92,96.5),("HuangZhong",29,65,85,100)],
    dtype=persontype)
ages = peoples[:]['age']
chineses = peoples[:]['chinese']
maths = peoples[:]['math']
englishs = peoples[:]['english']
print(np.mean(ages))
print(np.mean(chineses))
print(np.mean(maths))
print(np.mean(englishs))

28.25
77.5
93.25
93.75


In [74]:
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5,endpoint=True, retstep=False, dtype=None)
print(x1)
print(x2)
print(np.add(x1, x2))
print(np.subtract(x1, x2))
print(np.multiply(x1, x2))
print(np.divide(x1, x2))
print(np.power(x1, x2))
print(np.remainder(x1, x2))

[1 3 5 7 9]
[1. 3. 5. 7. 9.]
[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


In [80]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.amin(a))
print(np.amin(a,0))
print(np.amin(a,1))
print(np.amax(a))
print(np.amax(a,0))
print(np.amax(a,1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [85]:
a = np.arange(4).reshape((2,2))
print(a)
print(np.amax(a)          ) # Maximum of the flattened array)
print(np.amax(a, axis=0)  ) # Maxima along the first axis)
print(np.amax(a, axis=1)   )# Maxima along the second axis)

[[0 1]
 [2 3]]
3
[2 3]
[1 3]


In [86]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.ptp(a))
print(np.ptp(a,0))
print(np.ptp(a,1))

8
[6 6 6]
[2 2 2]


In [87]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.percentile(a, 50))
print(np.percentile(a, 50, axis=0))
print(np.percentile(a, 50, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [99]:
a = np.array([[10, 7, 4], [3, 2, 1]])
print(a)
print(np.percentile(a, 50))
print(np.percentile(a, 50, axis=0))
print(np.percentile(a, 50, axis=1))
print( np.percentile(a, 50, axis=1, keepdims=True))

m = np.percentile(a, 50, axis=0)
out = np.zeros_like(m)
print(np.percentile(a, 50, axis=0, out=out))
print(m)
b = a.copy()
print(np.percentile(b, 50, axis=1, overwrite_input=True))
# assert not np.all(a == b)

[[10  7  4]
 [ 3  2  1]]
3.5
[6.5 4.5 2.5]
[7. 2.]
[[7.]
 [2.]]
[6.5 4.5 2.5]
[6.5 4.5 2.5]
[7. 2.]


In [100]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# 求中位数
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))
# 求平均数
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]


In [101]:
a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
print(np.average(a))
print(np.average(a,weights=wts))


2.5
3.0


In [130]:
data = np.arange(1,5)
print(np.average(data))
print(np.average(range(1,11), weights=range(10,0,-1),returned = True))
data2 = np.arange(6).reshape((3,2))
print(data2)

2.5
(4.0, 55.0)
[[0 1]
 [2 3]
 [4 5]]


In [131]:
a = np.array([1,2,3,4])
print(np.std(a))
print(np.var(a))


1.118033988749895
1.25


In [132]:
a = np.array([[4,3,2],[2,4,1]])
print(np.sort(a))
print(np.sort(a, axis=None))
print(np.sort(a, axis=0)  )
print(np.sort(a, axis=1)  )

[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]


In [140]:
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 20 00:51:28 2019

@author: Dachun Li
"""
import numpy as np


persontype = np.dtype({
    'names':['name', 'chinese','english','math' ],
    'formats':['S32', 'i', 'i', 'i']})
peoples = np.array([        
        ("ZhangFei",66,65,30),("GuanYu",95,85,98),
       ("ZhaoYun",93,92,96),("HuangZhong",90,88,77),
       ("DianWei",80,90,90)],dtype=persontype)
#指定的竖列
name = peoples[:]['name']
chinese = peoples[:]['chinese']
english = peoples[:]['english']
math = peoples[:]['math']
#定义函数用于显示每一排的内容
def show(name,cj):
    print('{} | {} | {} | {} | {} | {} '
          .format(name,np.mean(cj),np.min(cj),np.max(cj),np.var(cj),np.std(cj)))

print("科目 | 平均成绩 | 最小成绩 | 最大成绩 | 方差 | 标准差")
show("语文", chinese)
show("英语", english)
show("数学", math)

print("排名:")
#用sorted函数进行排序
ranking = sorted(peoples,key=lambda x:x[1]+x[2]+x[3], reverse=True)
print(ranking)


科目 | 平均成绩 | 最小成绩 | 最大成绩 | 方差 | 标准差
语文 | 84.8 | 66 | 95 | 114.96000000000001 | 10.721940122944169 
英语 | 84.0 | 65 | 92 | 95.6 | 9.777525249264253 
数学 | 78.2 | 30 | 98 | 634.56 | 25.19047439013406 
排名:
[(b'ZhaoYun', 93, 92, 96), (b'GuanYu', 95, 85, 98), (b'DianWei', 80, 90, 90), (b'HuangZhong', 90, 88, 77), (b'ZhangFei', 66, 65, 30)]
